"""Train the Stage 1 ML detector: TF-IDF (word + char n-grams) -> LogisticRegression.

WHY THIS MODEL
--------------
It is the explainable baseline. It trains in seconds on CPU, the artifact is a
few MB, and inference is well under a millisecond, so it can sit in the request
path in front of the LLM call. Character n-grams matter here: they pick up
"1gn0r3" and "I.g.n.o.r.e" as a side effect of the representation, which the
regex layer only handles because sanitize_input() de-obfuscates by hand.

It is also a floor to beat. Report it alongside any transformer you train
later; "the simple baseline scored X, the transformer scored Y" is a far
stronger result than one number on its own.

DATA
----
Prefers public prompt-injection datasets when `datasets` is installed and
huggingface.co is reachable (--hf). Otherwise falls back to the bundled
data/seed_corpus.jsonl, which is generated by build_seed_corpus.py and is a
scaffold, not a research result — see that file's docstring.

Public sets worth pulling in (check each licence first):
    qualifire/prompt-injections-benchmark
    jackhhao/jailbreak-classification
    S-Labs/prompt-injection-dataset
    deepset/prompt-injections

Whatever the source, oversample HARD NEGATIVES: legitimate security and IT
questions containing attack vocabulary. Public sets pair attacks against
generic benign chat, and a model trained on that learns "mentions passwords ->
attack" — the trigger-word bias measured by InjecGuard (arXiv:2410.22770).

THE TEST SETS ARE NOT TRAINING DATA
-----------------------------------
evaluation.py's TEST_CASES and the held-out prompts in
tests/test_generalization.py are held out permanently. This script refuses to
run if any training row appears in either, and reports against them at the end.

Usage:
    python train_detector.py                # seed corpus
    python train_detector.py --hf           # add public datasets if reachable
    python train_detector.py --out models/detector.joblib
"""

import argparse
import json
import os
import re
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import joblib
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import FeatureUnion, Pipeline

HERE = os.path.dirname(os.path.abspath(__file__))
SEED_CORPUS = os.path.join(HERE, "data", "seed_corpus.jsonl")
DEFAULT_OUT = os.path.join(HERE, "models", "detector.joblib")
RANDOM_STATE = 20260921

# Public datasets to try under --hf: (repo id, text column, label column)
HF_DATASETS = [
    ("qualifire/prompt-injections-benchmark", "text", "label"),
    ("jackhhao/jailbreak-classification", "prompt", "type"),
    ("S-Labs/prompt-injection-dataset", "text", "label"),
]


def _normalize(text):
    """Key for duplicate and contamination checks — not used for training."""
    return re.sub(r"[^a-z0-9]+", " ", text.lower()).strip()


# =============================================================================
# Data
# =============================================================================

def load_seed():
    rows = []
    with open(SEED_CORPUS, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def load_hf():
    """Best-effort public datasets. Returns [] if unavailable — never fatal."""
    try:
        from datasets import load_dataset
    except ImportError:
        print("  `datasets` not installed — skipping public datasets")
        print("  install with: pip install datasets")
        return []

    rows = []
    for repo, text_col, label_col in HF_DATASETS:
        try:
            ds = load_dataset(repo, split="train")
        except Exception as exc:  # network, auth, gated repo, renamed column
            print(f"  {repo}: unavailable ({type(exc).__name__}) — skipped")
            continue

        added = 0
        for item in ds:
            text = item.get(text_col)
            raw = item.get(label_col)
            if not text:
                continue
            if isinstance(raw, str):
                label = 1 if raw.strip().lower() in {
                    "jailbreak", "injection", "malicious", "attack", "1", "true"
                } else 0
            else:
                label = int(bool(raw))
            rows.append({"text": text, "label": label, "source": repo})
            added += 1
        print(f"  {repo}: {added} rows")
    return rows


def held_out_texts():
    """Every prompt that must never be trained on."""
    out = set()

    import evaluation
    for case in evaluation.TEST_CASES:
        out.add(_normalize(case["prompt"]))

    try:
        sys.path.insert(0, os.path.join(HERE, "tests"))
        import test_generalization as tg
        for name in ("SAFE_HOLDOUT", "MALICIOUS_HOLDOUT"):
            for prompt in getattr(tg, name, []):
                out.add(_normalize(prompt))
    except Exception as exc:
        print(f"  ! could not load tests/test_generalization.py ({type(exc).__name__}) — "
              f"contamination check covers evaluation.py only")

    return out


def prepare(rows, forbidden):
    """Deduplicate, then refuse to proceed if any row is a held-out prompt."""
    seen, clean, leaked = set(), [], []
    for row in rows:
        key = _normalize(row["text"])
        if not key or key in seen:
            continue
        seen.add(key)
        if key in forbidden:
            leaked.append(row["text"])
            continue
        clean.append(row)

    if leaked:
        print(f"\nCONTAMINATION: {len(leaked)} training row(s) appear in a held-out set.")
        for text in leaked[:10]:
            print(f"    {text!r}")
        raise SystemExit(
            "Refusing to train. A model trained on its own test set produces a "
            "number that means nothing. Remove these rows and re-run."
        )
    return clean


# =============================================================================
# Model
# =============================================================================

def build_pipeline():
    """Word n-grams carry phrasing; char n-grams survive obfuscation."""
    return Pipeline([
        ("features", FeatureUnion([
            ("word", TfidfVectorizer(
                analyzer="word", ngram_range=(1, 2), min_df=1,
                sublinear_tf=True, lowercase=True, strip_accents="unicode")),
            ("char", TfidfVectorizer(
                analyzer="char_wb", ngram_range=(3, 5), min_df=1,
                sublinear_tf=True, lowercase=True, strip_accents="unicode")),
        ])),
        ("clf", LogisticRegression(
            max_iter=2000, C=4.0,
            class_weight="balanced",       # benign is the smaller class here
            random_state=RANDOM_STATE)),
    ])


def choose_threshold(pipe, X_val, y_val):
    """Lowest threshold that yields zero false positives on validation.

    Precision first, deliberately. This layer can block a request outright, and
    a local block is never reviewed by the LLM behind it — so a false positive
    is unrecoverable at runtime, while a miss still gets a second opinion.
    """
    probs = pipe.predict_proba(X_val)[:, 1]
    best = 0.95
    for threshold in np.arange(0.50, 0.96, 0.01):
        predicted = probs >= threshold
        false_pos = int(((predicted == 1) & (np.array(y_val) == 0)).sum())
        if false_pos == 0:
            best = float(threshold)
            break
    return round(max(0.50, min(best, 0.95)), 2)


def report_against(pipe, threshold, name, prompts, labels):
    probs = pipe.predict_proba(prompts)[:, 1]
    predicted = (probs >= threshold).astype(int)
    labels = np.array(labels)
    fp = int(((predicted == 1) & (labels == 0)).sum())
    fn = int(((predicted == 0) & (labels == 1)).sum())
    correct = int((predicted == labels).sum())
    print(f"  {name:<34} {correct}/{len(labels)}   FP={fp}  FN={fn}")
    return {"total": len(labels), "correct": correct, "fp": fp, "fn": fn}


# =============================================================================

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hf", action="store_true",
                    help="also pull public datasets from Hugging Face")
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    print("Loading data")
    rows = load_seed()
    print(f"  seed corpus: {len(rows)} rows")
    if args.hf:
        rows += load_hf()

    forbidden = held_out_texts()
    print(f"  held-out prompts protected: {len(forbidden)}")
    rows = prepare(rows, forbidden)

    texts = [r["text"] for r in rows]
    labels = [r["label"] for r in rows]
    n_mal = sum(labels)
    print(f"  training rows: {len(rows)}  ({n_mal} malicious, {len(rows) - n_mal} benign)")
    if len(rows) < 100:
        print("  ! very small corpus — treat every number below as provisional")

    X_train, X_val, y_train, y_val = train_test_split(
        texts, labels, test_size=0.25, random_state=RANDOM_STATE, stratify=labels)

    print("\nTraining")
    started = time.perf_counter()
    pipe = build_pipeline()
    pipe.fit(X_train, y_train)
    print(f"  fit in {time.perf_counter() - started:.2f}s")

    threshold = choose_threshold(pipe, X_val, y_val)
    print(f"  block threshold: {threshold}  (lowest with no validation false positives)")

    print("\nValidation split")
    print(classification_report(
        y_val, (pipe.predict_proba(X_val)[:, 1] >= threshold).astype(int),
        target_names=["benign", "malicious"], zero_division=0))

    # Held-out sets. Never trained on; this is the only honest read.
    print("Held-out (never trained on)")
    import evaluation
    metrics = {"threshold": threshold, "held_out": {}}
    metrics["held_out"]["evaluation.py"] = report_against(
        pipe, threshold, "evaluation.py TEST_CASES",
        [c["prompt"] for c in evaluation.TEST_CASES],
        [1 if c["label"] == "MALICIOUS" else 0 for c in evaluation.TEST_CASES])

    try:
        sys.path.insert(0, os.path.join(HERE, "tests"))
        import test_generalization as tg
        metrics["held_out"]["safe_holdout"] = report_against(
            pipe, threshold, "test_generalization SAFE",
            list(tg.SAFE_HOLDOUT), [0] * len(tg.SAFE_HOLDOUT))
        metrics["held_out"]["malicious_holdout"] = report_against(
            pipe, threshold, "test_generalization MALICIOUS",
            list(tg.MALICIOUS_HOLDOUT), [1] * len(tg.MALICIOUS_HOLDOUT))
    except Exception as exc:
        print(f"  ! held-out generalization set unavailable ({type(exc).__name__})")

    sample = ["How should we store API keys securely?"] * 200
    started = time.perf_counter()
    pipe.predict_proba(sample)
    per_call = (time.perf_counter() - started) / len(sample) * 1000
    print(f"\n  inference: {per_call:.3f} ms per prompt (batched)")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    joblib.dump({
        "pipeline": pipe,
        "threshold": threshold,
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "n_rows": len(rows),
        "sources": sorted({r.get("source", "unknown") for r in rows}),
        "metrics": metrics,
    }, args.out, compress=3)

    size_mb = os.path.getsize(args.out) / 1e6
    print(f"\nSaved {args.out} ({size_mb:.2f} MB)")
    if not args.hf:
        print("Trained on the seed corpus alone. Re-run with --hf and real public "
              "data before quoting these numbers anywhere.")


if __name__ == "__main__":
    main()
